[package]
name = "katas"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.2"

[[bin]]
name = "katas"
path = "src/main.rs"

[[bin]]
name = "advent_starter"
path = "src/advent_of_code/advent_starter.rs"